<div class="container">
    <h1><?php echo $this->__('Doi & Tra hang') ?></h1>
    <form action="<?php echo $this->getUrl('return/index/save') ?>" method="post" id="form-validate">
        <div class="fieldset">
            <ul class="form-list">
                <?php
                $sessionCustomer = Mage::getSingleton("customer/session");
                if(!$sessionCustomer->isLoggedIn()) {
                    ?>
                    <li class="fields">
                        <div class="customer-name">
                            <div class="field name-firstname">
                                <label for="firstname" class="required"><em>*</em>Firstname</label>
                                <div class="input-box">
                                    <input type="text" name="firstname" value="" class="input-text required-entry"/>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="customer-name">
                            <div class="field name-firstname">
                                <label for="firstname" class="required"><em>*</em>Lastname</label>
                                <div class="input-box">
                                    <input type="text" name="lastname" value="" class="input-text required-entry" />
                                </div>
                            </div>
                        </div>
                    </li>
                    <?php
                }
                ?>
                <li>
                    <label for="firstname" class="required"><em>*</em>Customer ID </label>
                    <div class="input-box">
                        <input type="text" name="customer" value="<?php
                        if(Mage::getSingleton('customer/session')->isLoggedIn())
                        {
                            $customerData = Mage::getSingleton('customer/session')->getCustomer();
                            echo $customerData->getId();
                        }
                        ?>"  class="input-text required-entry"/>
                    </div>
                    <label for="firstname" class="required"><em>*</em>Order ID</label>
                    <div class="input-box">
                        <input type="text" name="oder" value="" />
                    </div>
                    <label for="firstname" class="required"><em>*</em>Pass SKU</label>
                    <div class="input-box">
                        <input type="text" name="sku" value=""  />
                    </div>
                    <label><?php echo $this->__('Reason') ?></label>
                    <div class="input-box">
                       <?php  echo $this->dropReturn(); ?>
                    </div>
                    <label><?php echo $this->__('Upload') ?></label>
                    <div class="input-box">
                        <input type="text" name="image" value="" class="input-text required-entry" />
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
    </form>
</div>



<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('form-validate');
    //]]>
</script>