<?php
$unique = Mage::app()->getRequest()->getParam('unique');
$model = $this->getReturn();
$comment = $this->getCommentReturn($model['return_id']);

?>

<div class="page-title">

    <p>First Name : <?php echo $model['firstname']?></p>
    <p>Last Name : <?php echo $model['lastname']?></p>
    <p>Customer : <?php echo $model['customer']?></p>
    <p>Oder : <?php echo $model['oder']?></p>
    <p>Sku : <?php echo $model['sku']?></p>
    <p>Notes : <?php echo $model['comment']?></p>
    <p>Created : <?php echo $model['created_at']?></p>

    <form action="<?php echo $this->getUrl('return/index/add') ?>" method="post" id="form-validate">
        <label><?php echo $this->__('COMMENT') ?></label>
        <div class="input-box">
            <input type="text" name="comment" value="" class="input-text required-entry" />
            <input type="hidden" name="return_id" value="<?php echo $model['return_id']?>" class="input-text required-entry" />
            <input type="hidden" name="unique" value="<?php echo $unique?>" class="input-text required-entry" />
        </div>
        <div class="buttons-set">
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>

        </div>
        <div id="list_comment" style="clear: both">
            <ul>
                <?php foreach ($comment as $comments):?>
                    <li><?php echo $comments['comment'];?></li>
                    <li><?php echo $comments['created_at'];?></li>
                    <p>________________________________________</p>
                <?php endforeach;?>
            </ul>
        </div>
    </form>


</div>
