<?php
/**
 * Created by PhpStorm.
 * User: DTN
 * Date: 27/04/2016
 * Time: 4:08 CH
 */
class  Giang_Blog_Block_Adminhtml_Registries_Edit_Form extends  Mage_Adminhtml_Block_Widget_Form{
    protected function _prepareForm()
    {
        $form = new Varien_Data_Form(array(
            'id'=>'edit_form',
            'action'=>$this->getUrl('*/*/save',array(
                'id' =>$this->getRequest()->getParam('id')
            )),
            'method'=>'post',
            'enctype'=>'multipart/form-data'
        ));
        $form->setUseContainer(true);
        $this->setForm($form);
        $data = null;
        if(Mage::getSingleton('adminhtml/session')->getFormData()){
            $data = Mage::getSingleton('adminhtml/session')->getFormData();
            Mage::getSingleton('adminhtml/session')->setFormData(null);
        }elseif(Mage::registry('registry_data')){
            $data = Mage::registry('registry_data')->getData();
        }
            $fieldset = $form->addFieldset('registry_form',array('legend'=>Mage::helper('giang_blog')->__('Gift Registry information')));


            $fieldset->addField('fullname','text',array(
                'label'  => Mage::helper
                ('giang_blog')->__('Full Name'),
                'class'  => 'required-entry',
                'name'   => 'fullname'
            ));

            $fieldset->addField('username','text',array(
                'label'  => Mage::helper
                ('giang_blog')->__('User Name'),
                'class' => 'required-entry',
                'name'  => 'username'
            ));

            $fieldset->addField('password','text',array(
                'label' => Mage::helper
                ('giang_blog')->__('Pass Word'),
                'class' => 'required-entry',
                'name'  => 'password'
            ));
            $form->setValues($data);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}















