<?php  $data = $this->getData();
        var_dump($data);
?>


<div class="page-title">
    <h1><?php $this->__('Edit') ?></h1>
</div>
<form method="post" action="<?php echo $this->getUrl('giang/blog/update').'?user_id='.$data['user_id'] ?>" autocomplete="off" id="form-validate" class="scaffold-form" enctype="multipart/form-data" >
    Full name:
    <input type="text" name="fullname" value="<?php echo  $data['fullname']?>" />  <br>
    User name:
    <input type="text" name="username" value="<?php echo  $data['username']?>"/>  <br>
    Pass word:
    <input type="text" name="password" value="<?php echo  $data['password']?>"/>  <br>

    <button type="submit" > Update </button>
</form>