<div class="page-title">
    <h1>Dang ki</h1>
</div>
<form method="post" action="<?php echo $this->getUrl('giang/blog/save') ?>" autocomplete="off" id="form-validate" class="scaffold-form" enctype="multipart/form-data" >
    Full name:
    <input type="text" name="fullname" />  <br>
    User name:
    <input type="text" name="username" />  <br>
    Pass word:
    <input type="password" name="password" />  <br>
    <button type="submit" > SEND </button>
</form>
