<?php
/**
 * Created by PhpStorm.
 * User: DTN
 * Date: 27/04/2016
 * Time: 4:08 CH
 */
class  Dtn_Return_Block_Adminhtml_Registries_Edit_Form extends  Mage_Adminhtml_Block_Widget_Form{
    protected function _prepareForm()
    {
        $form = new Varien_Data_Form(array(
            'id'=>'edit_form',
            'action'=>$this->getUrl('*/*/save',array(
                'id' =>$this->getRequest()->getParam('id')
            )),
            'method'=>'post',
            'enctype'=>'multipart/form-data'
        ));
        $form->setUseContainer(true);
        $this->setForm($form);
        $data = null;
        if(Mage::getSingleton('adminhtml/session')->getFormData()){
            $data = Mage::getSingleton('adminhtml/session')->getFormData();
            Mage::getSingleton('adminhtml/session')->setFormData(null);
        }elseif(Mage::registry('registry_data')){
            $data = Mage::registry('registry_data')->getData();
        }
        $fieldset = $form->addFieldset('registry_form',array('legend'=>Mage::helper('dtn_return')->__('Gift Registry information')));


        $fieldset->addField('firstname','text',array(
            'label'  => Mage::helper
            ('dtn_return')->__('First Name'),
            'class'  => 'required-entry',
            'name'   => 'firstname'
        ));

        $fieldset->addField('lastname','text',array(
            'label'  => Mage::helper
            ('dtn_return')->__('Last Name'),
            'class' => 'required-entry',
            'name'  => 'lastname'
        ));

        $fieldset->addField('unique','text',array(
            'label' => Mage::helper
            ('dtn_return')->__('Unique'),
            'class' => 'required-entry',
            'name'  => 'unique'
        ));
        $form->setValues($data);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}















