<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-customer-view">
            <?php echo $this->__('Blog Post') ?>
        </h4>
    </div>
    <table cellspacing="2" class="tab_blogpost_list">
        <tr>
            <td>
                Nothing here
            </td>
        </tr>
    </table>
    <?php echo $this->getChildHtml('tab_blogpost_list'); ?>
</div>