<?php
/**
 * Created by PhpStorm.
 * User: DTN
 * Date: 27/04/2016
 * Time: 12:47 CH
 */
class Giang_Blog_Block_Adminhtml_Registries_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    public function __construct()
    {
        parent::__construct();
        $this->setId('user_id');
        $this->setDefaultSort('user_id');
        $this->setDefaultDir('ASC');
        $this->setSaveParametersInSession(true);
    }

    protected function _prepareCollection()
    {
        $collection = Mage::getModel('giang_blog/blogpost')->getCollection();
        $this->setCollection($collection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }

    protected function _prepareColumns()
    {
        $this->addColumn('user_id', array(
            'header' => Mage::helper
            ('giang_blog')->__('User Id'),
            'width' => 50,
            'index' => 'user_id',
            'sortable' => false,
        ));

        $this->addColumn('fullname', array(
            'header' => Mage::helper
            ('giang_blog')->__('Full Name'),
            'width' => 50,
            'index' => 'fullname',
            'sortable' => false,
        ));

        $this->addColumn('username', array(
            'header' => Mage::helper
            ('giang_blog')->__('User Name'),
            'width' => 50,
            'index' => 'username',
            'sortable' => false,
        ));

        $this->addColumn('password', array(
            'header' => Mage::helper
            ('giang_blog')->__('Pass Word'),
            'width' => 50,
            'index' => 'password',
            'sortable' => false,
        ));
        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }

    protected function _prepareMassaction()
    {
        $this->setMassactionIdField('user_id');
        $this->getMassactionBlock()->
        setFormFieldName('registries');
        $this->getMassactionBlock()->addItem('delete', array(
            'label'
            => Mage::helper
            ('giang_blog')->__('Delete'),
            'url'
            => $this->getUrl('*/*/massDelete'),
            'confirm'
            => Mage::helper
            ('giang_blog')->__('Are you sure?')
        ));
        return $this;
    }

    public function getRowUrl($row)
    {
        return $this->getUrl('*/*/edit', array
        ('id' => $row->getUserId()));
    }

}






























