<?php
/**
 * Created by PhpStorm.
 * User: DTN
 * Date: 27/04/2016
 * Time: 12:47 CH
 */
class Dtn_Return_Block_Adminhtml_Registries_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    public function __construct()
    {
        parent::__construct();
        $this->setId('return_id');
        $this->setDefaultSort('return_id');
        $this->setDefaultDir('ASC');
        $this->setSaveParametersInSession(true);


        $this->setSaveParametersInSession(true);
        $this->setUseAjax(true);
    }

    protected function _prepareCollection()
    {
        $collection = Mage::getModel('dtn_return/return')->getCollection();
        $this->setCollection($collection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }

    protected function _prepareColumns()
    {
        $this->addColumn('return_id', array(
            'header' => Mage::helper
            ('dtn_return')->__('Return Id'),
            'width' => 50,
            'index' => 'return_id',
            'sortable' => false,
        ));
        $this->addColumn('unique', array(
            'header' => Mage::helper
            ('dtn_return')->__('Unique'),
            'width' => 50,
            'index' => 'firstname',
            'sortable' => false,
        ));
        $this->addColumn('firstname', array(
            'header' => Mage::helper
            ('dtn_return')->__('First Name'),
            'width' => 50,
            'index' => 'firstname',
            'sortable' => false,
        ));
        $this->addColumn('lastname', array(
            'header' => Mage::helper
            ('dtn_return')->__('Last Name'),
            'width' => 50,
            'index' => 'lastname',
            'sortable' => false,
        ));

        $this->addColumn('customer', array(
            'header' => Mage::helper
            ('dtn_return')->__('Customer'),
            'width' => 50,
            'index' => 'customer',
            'sortable' => false,
        ));
        $this->addColumn('oder', array(
            'header' => Mage::helper
            ('dtn_return')->__('Oder'),
            'width' => 50,
            'index' => 'oder',
            'sortable' => false,
        ));
        $this->addColumn('sku', array(
            'header' => Mage::helper
            ('dtn_return')->__('Sku'),
            'width' => 50,
            'index' => 'sku',
            'sortable' => false,
        ));
        $this->addColumn('notes', array(
            'header' => Mage::helper
            ('dtn_return')->__('Notes'),
            'width' => 50,
            'index' => 'notes',
            'sortable' => false,
        ));
        $this->addColumn('pending', array(
            'header' => Mage::helper
            ('dtn_return')->__('Pending'),
            'width' => 50,
            'index' => 'pending',
            'sortable' => false,
        ));
        $this->addColumn('created_at', array(
            'header' => Mage::helper
            ('dtn_return')->__('Created At'),
            'width' => 50,
            'index' => 'created_at',
            'sortable' => false,
        ));
        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }

    protected function _prepareMassaction()
    {
        $this->setMassactionIdField('return_id');
        $this->getMassactionBlock()->setFormFieldName('registries');
        $this->getMassactionBlock()->addItem('delete', array(
            'label'
            => Mage::helper
            ('giang_blog')->__('Delete'),
            'url'
            => $this->getUrl('*/*/massDelete'),
            'confirm'
            => Mage::helper
            ('dtn_return')->__('Are you sure?')
        ));
        return $this;
    }

    public function getRowUrl($row)
    {
        return $this->getUrl('*/*/edit', array
        ('id' => $row->getUserId()));
    }




    public function getGridUrl()
    {
        return $this->getUrl('*/*/grid', array('_current'=>true));
    }

}






























